### ISSUE TITLE
deleteUser command should delete a user and clear their data from the file.

### ISSUE THREAD

**Issue by tngok-wustl** [eroosendahl/237_Health_Tracker#29]
Example usage:

deleteUser <some username>

Console output:
Are you sure you wish to delete user <some username>? (y/n)
*user inputs y*

Then the command deletes the user and all of its data, and move users below and their data up.  

One way to do this could be starting with the row of the user you are deleting, and going through the list of users from the command prompt, finding the user with the row just under the one we are deleting, and moving them up, then recursively or otherwise do the exact same thing, but starting from the row of the user we just moved up, until we can't find any users with rows below our current.  (below in this case meaning higher int value for row since csv rows grow down).  This relies on properly updating the User's user.row values so they are always consistent.

**Comment by eroosendahl** [comment]
Strange that all my comments on these issues are showing as from tngok-wustl after he converted the item to an issue...  I guess it marks who converts the comment from who converted it to the issue, not who originally made the item and wrote the comment.
